# Generated by Django 3.0.5 on 2020-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200425_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=600),
        ),
    ]
