# Generated by Django 3.0.5 on 2020-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Видеотека', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=300, verbose_name='Путь'),
        ),
    ]
